services:
  redis:
    image: docker.io/bitnami/redis:5.0.14
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - cache:/data
    ports:
      - '6379:6379'
    networks:
      - api_network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - api_network
    ports:
      - "9200:9200"
    restart: always

  postgres_etl:
    image: postgres:13.3-alpine
    container_name: postgres_etl
    env_file:
      - .env
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - api_network
    ports:
      - "5432:5432"
    restart: always

  etl:
    container_name: etl
    volumes:
      - etl_logs:/usr/src/app/logs/
    build: ./etl
    env_file:
      - .env
    networks:
      - api_network
    depends_on:
      - elasticsearch
      - postgres_etl
    restart: always

  fastapi:
    container_name: fastapi
    build: ./fastapi-solution
    env_file:
      - .env
    networks:
      - api_network
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana-container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - api_network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  nginx:
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/fastapi.conf:/etc/nginx/conf.d/fastapi.conf:ro
    depends_on:
      - fastapi
    ports:
      - "80:80"
    restart: always

networks:
  api_network:
    driver: bridge

volumes:
  postgres_data:
  etl_logs:
  es_data:
  cache:
