services:
  redis:
    image: docker.io/bitnami/redis:5.0.14
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - api_network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - api_network
    ports:
      - "9200:9200"
    restart: always

  postgres_etl:
    image: postgres:13.3-alpine
    container_name: postgres_etl
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - api_network
    ports:
      - "5432:5432"
    restart: always

  etl:
    container_name: etl
    volumes:
      - etl_logs:/usr/src/app/logs/
    build: ./etl
    env_file:
      - .env
    networks:
      - api_network
    depends_on:
      - elasticsearch
      - postgres_etl
    restart: always

  fastapi:
    container_name: fastapi
    build: ./fastapi-solution
    env_file:
      - .env
    networks:
      - api_network
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  api_network:

volumes:
  postgres_data:
  etl_logs: