FROM python:3.9
WORKDIR /fastapi
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY requirements.txt .
RUN  pip install --upgrade pip \
     && pip install -r requirements.txt
COPY src .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0"]